# -*- coding: utf-8 -*-
"""create_features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rUwPCoSuWG1BFERv8Y4Xp0fo7cHMtvXJ
"""

def transform_features(df):
    #оставляем только 0 и 1 у гендера
    df['Gender'] = df['Gender'].apply(lambda x: 1 if (x == 'Male') or (x == '1.0') else 0)



    df['activity_index'] = (
        df['Exercise Hours Per Week'] *
        df['Physical Activity Days Per Week']
    )

    #новый признак риск здоровья
    df['health_risk'] = (
      df['Smoking'] +
      df['Alcohol Consumption'] +
      df['Sedentary Hours Per Day']
  )

    df['pulse_pressure'] = (
    df['Systolic blood pressure'] -
    df['Diastolic blood pressure']
)

    #наши новые бинарные признаки
    df['high_bmi'] = (df['BMI'] > 0.6).astype(int)
    df['high_chol'] = (df['Cholesterol'] > 0.7).astype(int)
    df['high_trig'] = (df['Triglycerides'] > 0.7).astype(int)


    #удяляем наши неинформативные признаки
    df = df.drop(columns=[
        'Unnamed: 0',
        'CK-MB',
        'Troponin',
        'Blood sugar',
        'Systolic blood pressure',
        'Diastolic blood pressure',
        'Income',
        'Exercise Hours Per Week',
        'Physical Activity Days Per Week'

    ])

    return df