# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAJj6iAtvmlH2kGZgiM3pA8T-f6p6plj

#FastAPI приложение
"""

from fastapi import FastAPI, UploadFile
from features import transform_features
import pandas as pd
import joblib
import io
import os

app = FastAPI()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
model_path = os.path.join(BASE_DIR, 'model.pkl')

model = joblib.load(model_path)

@app.post('/predict')
async def predict(file: UploadFile):
    contents = await file.read()
    df = pd.read_csv(io.BytesIO(contents))

    ids = df['id']
    X = df.drop(columns=['id'])

    #наши преобразования
    X = transform_features(X)

    preds = model.predict(X)

    result = pd.DataFrame({
        'id': ids,
        'prediction': preds
    })

    return result.to_dict(orient='records')