# -*- coding: utf-8 -*-
"""проект_М1-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_0CS1KVO2SnDFFTURLxHh6JXWWBiQgP

# **Общая информация и цель проекта**
В этом проекте предполагается работа с датасетом из открытого источника. Вам потребуется разработать модель машинного обучения, а также подготовить библиотеку и интерфейс к ней для предсказания на тестовой выборке. В начале проекта вам будет доступен обучающий датасет и тестовый датасет, не содержащий правильных ответов. Метрика на тестовом датасете будет измерена в ходе проверки работы. Также вам будет доступен скрипт, с помощью которого будет измеряться финальная метрика вашей модели.

__Описание исходных данных:__

*   id  - id
*   Антропометрические параметры:

          -  'Age' возраст
          -   'BMI' индекс массы тела
          -   'Income' доход
*   Привычки:

          -   'Smoking' курение
          -   'Alcohol Consumption' употребление алкоголя
          -   'Exercise Hours Per Week', 'Physical Activity Days Per Week' физич нагрузка часов и дней в неделю
          -   'Sedentary Hours Per Day' часы без активности в день
          -   'Sleep Hours Per Day' продолжительность сна
          -   'Diet' питание, 'Stress Level' уровень стресса
*   Давление:

          -   'Heart rate' пульс
          -   'Systolic blood pressure' систолическое давление
          -   'Diastolic blood pressure' диастолическое давление

*   Наличие хронических заболеваний:

          -  'Previous Heart Problems' предыдущие проблемы с сердцем
          -  'Diabetes' диабет
          -  'Family History' наследственные заболевания
          -  'Medication Use' принимаемые лекарства

*   Биохимия крови:

          -  'Cholesterol' холестерин
          -  'Blood sugar' уровень сахара в крови
          -  'Triglycerides' жиры в крови
          -  'CK-MB' фермент повреждения сердечной мышцы
          -  'Troponin' маркер инфаркта
*   Таргет:

           - 'Heart Attack Risk' высокий или низкий риск поражения сердца

__План работы:__  

1.   Исследовать датасет.
2.   Предобработать данные.
3.   Подготовить предсказания на тестовой выборке.
4.   Подготовить скрипты и библиотеки для обработки данных и предсказания на тестовой выборке.  
5. Написать инструмент для тестирования.

# Исследование данных (EDA)

В целом исследуем датасет для лучшего понимания природы данных:
- типы данных
- пропуски
- дубликаты
- распределения
- предположить, где может быть утечка данных
"""

#основные библиотеки
import pandas as pd
import numpy as np
import phik
import joblib

import seaborn as sns
import matplotlib.pyplot as plt

#это наши признаки
from features import transform_features

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from sklearn.metrics import recall_score, roc_auc_score, RocCurveDisplay, classification_report

RANDOM_STATE = 42

#считываем данные
train = pd.read_csv('heart_train.csv')
test = pd.read_csv('heart_test.csv')

"""Посмотрим на данные, в целом что из себя они представляют.

__Тип данных и описание__
"""

train.columns

print(train.head(5))

"""Для начала стоит __добавить описание по каждой колонке__ и распределить их по группам.  
Так нам будет легче работать в будущем.

__Что видим:__
- Колонка Unnamed: 0 не несет смысла, удалаяем.
- Heart Attack Risk - наш таргет действительно бинарный.
- Gender стоит тоже сделать категориальным 0 и 1.
- __!Может быть утечка данных__. У нас есть два нестандартных анализа в биохимии крови  - это 'CK-MB' (фермент повреждения сердечной мышцы) и
'Troponin' (маркер инфаркта), внимательно посмотрим на них.
- Есть колонки, которые в целом повторяют информацию между собой - это   'Exercise Hours Per Week', 'Physical Activity Days Per Week' физическая нагрузка часов и дней в неделю и 'Sedentary Hours Per Day' (часы без активности в день).
"""

train.info()

"""В некоторых колонках отсутсвуют значения, подробнее посмотрим на значения через describe()."""

print(train.describe().T)

"""__Что выделяется:__
1. Возраст закодирован 0 и 1. Возможно есть какой-то пороговое число после которого восрастает риск поражения сердца, допустим, до и после 45 лет.
2. В трех колонках! у нас константы по 25%, 50% и 75% - Blood sugar, CK-MB, Troponin. Посмотрим на их значения, очень подозрительно.
3. Есть пропуски в данных и это одинаковое количество. Посмотрим на эти колонки: Diabetes, Family History, Smoking, Obesity, Alcohol Consumption, Previous Heart Problems, Medication Use, Stress Level, Physical Activity Days Per Week. Возможно, их добавили позже в таблицу опроса пациентов.

__Проверим уникальные значения у наших подозрительных признаков 'Blood sugar', 'CK-MB', 'Troponin'__
"""

#посмотрим на эти три колонки, у которых константные признаки
for col in ['Blood sugar', 'CK-MB', 'Troponin']:
    print(col, train[col].nunique())

"""Возьмем их во внимаение!"""

train[['Exercise Hours Per Week',
       'Physical Activity Days Per Week',
       'Sedentary Hours Per Day']].corr()

"""Пока их оставим.

__Возможна ли утечка данных?__  

Есть два признака которые могут быть взяты уже после инфаркта - это 'CK-MB' (фермент повреждения сердечной мышцы) и 'Troponin' (маркер инфаркта). Построим графики и посмотрим на них.
"""

sns.boxplot(data=train, x='Heart Attack Risk (Binary)', y='Troponin')
plt.show()

sns.boxplot(data=train, x='Heart Attack Risk (Binary)', y='CK-MB')
plt.show()

"""Если посмотреть информацию по этим двум показателям в Интернете, то у здорового человека они должны быть приближены к 0 - это у 'Troponin' и 'CK-MB'.
Странно то, что они ближе около нуля в обоих классах - '0' и '1'. Совсем неинформативно для нашего предсказания!

В итоге:
- одинаковые распределения
- почти все значения окло нуля
- нет разделения классов

__РАСПРЕДЕЛЕНИЯ__
"""

num_cols = train.select_dtypes(include='number').columns

train[num_cols].hist(figsize=(20,15), bins=20)
plt.show()

"""__Что мы видим.__  

У нас так и остались наши проблемные признаки:
  - 'Blood sugar' - почти константный признак;
  - 'CK-MB' и 'Troponin' - пик около нуля.

Данные совсем неинформативные. Все-таки удалим их.

Интересно, что __числовые признаки__ уже находятся в диапазоне от 0 до 1, а значит, что данные уже __отмасштабированы!__

Бинарные признаки нормальные.  

У нашего таргета есть дисбаланс классов.

__Удаляем наши подозрительные признаки - 'CK-MB', 'Troponin', 'Blood sugar'__

__Дополнительно проверим колонки на корреляцию между собой:__

- Exercise Hours Per Week - физ нагрузка часов в неделю
- Physical Activity Days Per Week - в какие дни нагрузка

и

- Exercise Hours Per Week - сидячее время
- Physical Activity Days Per Week - сон

Потому что кажется, что они могут быть взаимозаменяемы.
"""

train[[
    'Exercise Hours Per Week',
    'Physical Activity Days Per Week',
    'Sedentary Hours Per Day',
    'Sleep Hours Per Day'
]].corr()

"""Нет, сильной корреляции не наблюдается.

Посмотрим на уникальные значения в __Gender__
"""

print(train['Gender'].unique())

"""Это две лишние категории, уберем их!  

- Для 'Male', '1.0' оставим 1  
- Для 'Female', '0.0' будет 0

Добвим новый признак - __риск здоровья__ и назовем train['health_risk']

Пульсовое давление = систолическое - диастолическое давление  
Добавим новый признак - __pulse_pressure__

Удалим лишние признаки и __добавим бинарные__
"""

train = transform_features(train)
test = transform_features(test)

train['high_bmi'] = (train['BMI'] > 0.6).astype(int)
train['high_chol'] = (train['Cholesterol'] > 0.7).astype(int)
train['high_trig'] = (train['Triglycerides'] > 0.7).astype(int)

test['high_bmi'] = (train['BMI'] > 0.6).astype(int)
test['high_chol'] = (train['Cholesterol'] > 0.7).astype(int)
test['high_trig'] = (train['Triglycerides'] > 0.7).astype(int)

train.nunique().sort_values()

"""__КОРРЕЛЯЦИЯ__

Будем проводить анализ с помощью Phik:

- проведем корреляционный анализ признаков у таблицы train.
- посмотрим на корреляцию с нашей целевой переменной ___Heart Attack__  
- в датасете есть много бинарных признаков  
- Phik более устойчивее к выбросам  
- Phik находит нелинейные зависимости  
"""

phik_corr = train.phik_matrix()

plt.figure(figsize=(14,10))
sns.heatmap(phik_corr, cmap='coolwarm')
plt.title('Phik correlation')
plt.show()

"""__Какие есть зависимости:__

1. Есть зависимость между диетой и количеством сна.
2. Курение тоже сильно зависит от гендера.

Критической мультиколлинеарности нет!

#Подготовим данные
"""

#выделяем таргет и убираем его из обучения
X = train.drop(columns=['Heart Attack Risk (Binary)', 'id'])
y = train['Heart Attack Risk (Binary)']

#ставим stratify из-за дисбаланса в классах
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=RANDOM_STATE, stratify=y)

#наши категориальные и числовые признаки
cat_cols = ['Diet']
num_cols = [col for col in X.columns if col not in cat_cols]

"""# Pipeline"""

#для категориальных
cat_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ohe', OneHotEncoder(handle_unknown='ignore'))
])

#числовых
num_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

#объединяем
preprocessor = ColumnTransformer([
    ('cat', cat_pipe, cat_cols),
    ('num', num_pipe, num_cols)
])

#итоговый пайплайн: подготовка данных и модель
pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LogisticRegression(max_iter=2000))
])

param_grid = [
    {
        'model': [LogisticRegression(max_iter=2000)],
        'model__C': [0.1, 1, 10]
    },
    {
        'model': [SVC()],
        'model__C': [0.1, 1],
        'model__gamma': ['scale']
    },
    {
        'model': [CatBoostClassifier(verbose=0)],
        'model__depth': [4, 6],
        'model__learning_rate': [0.03, 0.1]
    }
]

#для автоматического подбора гиперпараметров
grid = GridSearchCV(
    pipe,
    param_grid=param_grid,
    cv=5,
    scoring='roc_auc',
    n_jobs=-1
)

grid.fit(X_train, y_train)

"""Посмотрим на наши результаты:"""

print('Best model:', grid.best_estimator_)
print('ROC-AUC (CV):', grid.best_score_)

"""__Тест__"""

best_model = grid.best_estimator_

y_proba = best_model.predict_proba(X_test)[:, 1]

print('ROC-AUC test:', roc_auc_score(y_test, y_proba))

"""__Посмотрим на ROC-кривую__"""

RocCurveDisplay.from_estimator(best_model, X_test, y_test)

for t in [0.5, 0.4, 0.3, 0.2]:
    y_pred = (y_proba > t).astype(int)
    print(f'threshold={t}, recall={recall_score(y_test, y_pred):.3f}')

"""__Сlassification report__"""

#оставляем threshold = 0.3, при recall=0.521
threshold = 0.3
y_pred = (y_proba > threshold).astype(int)

print(classification_report(y_test, y_pred))

"""Изменив threshold, у нас стало больше false positives и ниже accuracy, но в данной задаче __recall намного важнее__. Так как лучше перепроверить возможность сердечного приступа, чем его недосмотреть.

"""

#сохраним наши id
test_id = test['id']
test_features = test.drop(columns=['id'])

y_proba = best_model.predict_proba(test_features)[:, 1]

"""Файл предсказаний должен быть в csv формате и содержать 2 столбца:
- id
- prediction
"""

threshold = 0.3
y_pred_test = (y_proba > threshold).astype(int)

submission = pd.DataFrame({'id': test_id, 'prediction': y_pred_test})

submission.to_csv('submission.csv', index=False)

#наши предсказания
submission = pd.DataFrame({'id': test_id, 'prediction': y_proba})

submission.to_csv('submission.csv', index=False)

"""#Сохраняем модель"""

joblib.dump(best_model, 'model.pkl')